# Generated by Django 5.1.5 on 2025-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(upload_to='cs-images/'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news-images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='pj-images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.ManyToManyField(blank=True, to='members.label'),
        ),
    ]
