# Generated by Django 5.1.5 on 2025-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_courseimage_image_alter_newsimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.TextField(unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
