# Generated by Django 5.1.5 on 2025-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_course_title_remove_coursecontent_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='members.label'),
        ),
    ]
