# Generated by Django 5.1.5 on 2025-01-22 19:07

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_project_label'),
    ]

    operations = [
    
        migrations.AlterUniqueTogether(
            name='coursecontenttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseimage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='label',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='members.module'),
        ),
        migrations.CreateModel(
            name='ModuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('module', models.TextField(unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='members.module')),
            ],
            options={
                'verbose_name': 'module Translation',
                'db_table': 'members_module_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
        migrations.DeleteModel(
            name='CourseContentTranslation',
        ),
        migrations.DeleteModel(
            name='CourseImage',
        ),
    ]
