# Generated by Django 5.1.5 on 2025-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_coursecontenttranslation_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(default='http'),
            preserve_default=False,
        ),
    ]
