# Generated by Django 5.1.5 on 2025-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user-avaters/default.jpg', upload_to='user-avaters/'),
        ),
    ]
