# Generated by Django 5.1.5 on 2025-02-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
