# Generated by Django 5.1.5 on 2025-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user-avatars/default.jpg', upload_to='user-avatars/'),
        ),
    ]
