# Generated by Django 5.1.5 on 2025-02-07 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_label_created_by_remove_project_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='nlabel', to='members.newslabel'),
        ),
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='plabel', to='members.projectlabel'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('c_type', models.CharField(choices=[('project', 'Project'), ('news', 'News'), ('course', 'Course'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_obj', models.ManyToManyField(blank=True, to='members.course')),
                ('news_obj', models.ManyToManyField(blank=True, to='members.news')),
                ('project_obj', models.ManyToManyField(blank=True, to='members.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
