# Generated by Django 5.1.5 on 2025-02-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_news_label_project_label_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='members.news'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='members.news'),
        ),
    ]
