# Generated by Django 5.1.5 on 2025-02-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_newscontent_news_alter_newsimage_news'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newscontent',
            unique_together={('news', 'num')},
        ),
        migrations.AlterUniqueTogether(
            name='newsimage',
            unique_together={('news', 'num')},
        ),
    ]
