# Generated by Django 5.1.5 on 2025-02-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
